server.port=8090
spring.application.name=campaign-processor

spring.datasource.url=jdbc:postgresql://localhost:5432/analyzer
spring.datasource.username=cipher
spring.datasource.password=secret

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=campaign-processor-group
spring.kafka.consumer.auto-offset-reset=earliest

# Standard, clean deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Tell the JSON mapper to trust your domain
spring.kafka.consumer.properties.spring.json.trusted.packages=com.cipherlab.*

# THE FIX: Map the producer's class name straight to your local consumer class path
spring.kafka.consumer.properties.spring.json.type.mapping=com.cipherlab.caampaign_analytics.dto.CampaignEventMessage:com.cipherlab.campaign_processor.dto.CampaignEventMessage